from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$', 'warara.board.views.index'),
    (r'^move_article/$','warara.board.views.move_article'),
    (r'^(?P<board_name>[\w \[\]\.]+)/$', 'warara.board.views.list'),
    (r'^(?P<board_name>[\w \[\]\.]+)/write/$', 'warara.board.views.write'),
    (r'^(?P<board_name>[\w \[\]\.]+)/rss/$', 'warara.board.views.rss'),
    (r'^([\w \[\]\.]+)/([\d]+)/$', 'warara.board.views.read'),
    (r'^([\w \[\]\.]+)/([\d]+)/0/$','warara.board.views.read_root'),
    (r'^([\w \[\]\.]+)/([\d]+)/reply/$', 'warara.board.views.reply'),
    (r'^([\w \[\]\.]+)/([\d]+)/(\d+)/vote/(\+|\-)$', 'warara.board.views.vote'),
    (r'^([\w \[\]\.]+)/([\d]+)/(\d+)/scrap/$', 'warara.board.views.scrap'),
    (r'^([\w \[\]\.]+)/([\d]+)/(\d+)/unscrap/$', 'warara.board.views.unscrap'),
    (r'^([\w \[\]\.]+)/([\d]+)/(\d+)/delete/$', 'warara.board.views.delete'),
    (r'^([\w \[\]\.]+)/([\d]+)/(\d+)/destroy/$', 'warara.board.views.destroy'),
    (r'^([\w \[\]\.]+)/search/$', 'warara.board.views.search'),
#    (r'^([\w \[\]\.]+)/delete_file/$', 'warara.board.views.file_delete'),
    (r'^([\w \[\]\.]+)/([\d]+)/(\d+)/file/(\d+)/$', 'warara.board.views.file_download'),
)
